[versions]
agp = "8.4.2"
core = "3.4.1"
gson = "2.10.1"
kotlin = "1.9.20"
composeCompiler = "1.5.4"

compileSdk = "34"
targetSdk = "34"
minSdk = "24"

coreKtx = "1.13.1"
activityCompose = "1.9.0"
splashScreen = "1.0.1"
composeBom = "2024.02.01"
coil = "2.6.0"
constraint = "1.1.0-alpha13"

koin = "3.4.0"

lifecycle = "2.8.4"
navigationCompose = "2.8.5"

playServices = "4.4.1"
playServicesAuth = "20.1.0"

firebase-auth = "21.1.0"
firebase-firestore-ktx = "24.4.2"
firebase-storage-ktx = "20.0.1"

lottie= "4.1.0"
ktor=  "3.0.0-beta-1"
firebaseKtx = "0.2.1"
zxingAndroidEmbedded = "4.2.0"

[libraries]
#core
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }

#activity
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-core-splashscreen = { group = "androidx.core", name = "core-splashscreen", version.ref = "splashScreen" }

#ui
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-material3 = { group = "androidx.compose.material3", name = "material3" }
androidx-ui-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout-compose", version.ref = "constraint" }

core = { module = "com.google.zxing:core", version.ref = "core" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
io-coil = { group = "io.coil-kt", name = "coil-compose", version.ref = "coil" }

lottie-compose = { module = "com.airbnb.android:lottie-compose", version.ref = "lottie" }

#koin
koin-android = { module = "io.insert-koin:koin-android", version.ref = "koin" }
koin-androidx-compose = { module = "io.insert-koin:koin-androidx-compose", version.ref = "koin" }

#lifeCycle
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycle" }
androidx-lifecycle-runtime-compose = { group = "androidx.lifecycle", name = "lifecycle-runtime-compose", version.ref = "lifecycle" }

#navigation
androidx-navigation = { group = "androidx.navigation", name = "navigation-compose", version.ref = "navigationCompose" }

#ktor
ktorCore = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktorContentNegotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
ktorOkhttp = { module = "io.ktor:ktor-client-okhttp", version.ref = "ktor" }
ktorSerialization = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }
ktorLogger = { module = "io.ktor:ktor-client-logging", version.ref = "ktor" }
jsonSerialization = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version = "1.6.2" }

#googleService
play-services-auth = { module = "com.google.android.gms:play-services-auth", version.ref = "playServicesAuth" }

#firebase
firebase-auth = { module = "com.google.firebase:firebase-auth", version.ref = "firebase-auth" }
firebase-auth-ktx = { module = "com.google.firebase:firebase-auth-ktx", version.ref = "firebase-auth" }
firebase-firestore-ktx = { module = "com.google.firebase:firebase-firestore-ktx", version.ref = "firebase-firestore-ktx" }
firebase-storage-ktx = { module = "com.google.firebase:firebase-storage-ktx", version.ref = "firebase-storage-ktx" }
firebase-database-ktx = { module = "com.github.skydoves:firebase-database-ktx", version.ref = "firebaseKtx" }

# Dependencies of the included build-logic
android-gradle-plugin = { module = "com.android.tools.build:gradle", version.ref = "agp" }
kotlin-gradle-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
zxing-android-embedded = { module = "com.journeyapps:zxing-android-embedded", version.ref = "zxingAndroidEmbedded" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
google-play-services = { id = "com.google.gms.google-services", version.ref = "playServices" }
serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }

[bundles]
io = ["jsonSerialization", "ktorCore", "ktorContentNegotiation", "ktorOkhttp", "ktorSerialization", "ktorLogger"]


