[versions]
kotlin = "2.0.0"
agp = "8.4.2"
composePlugin = "1.7.0"
composeCompiler = "1.5.4"
gson = "2.10.1"
core = "3.4.1"

compileSdk = "34"
targetSdk = "34"
minSdk = "24"

coreKtx = "1.13.1"
activityCompose = "1.9.0"
splashScreen = "1.0.1"
composeBom = "2024.02.01"
coil = "3.0.4"
constraint = "1.1.0-alpha13"
lottie = "4.1.0"
lifecycle = "2.8.2"
navigation = "2.8.5"

zxingAndroidEmbedded = "4.2.0"

koin = "4.0.1"
ktor = "3.0.0-beta-1"
kotlinx-serialization = "1.6.2"
kotlinx-datetime = "0.6.1"
kotlinx-coroutines = "1.10.1"

playServices = "4.4.1"
playServicesAuth = "20.1.0"

firebase-auth = "21.1.0"
firebase-firestore-ktx = "24.4.2"
firebase-storage-ktx = "20.0.1"
firebaseKtx = "0.2.1"

[libraries]
#core
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }

#activity
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-core-splashscreen = { group = "androidx.core", name = "core-splashscreen", version.ref = "splashScreen" }

#ui
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-material3 = { group = "androidx.compose.material3", name = "material3" }
androidx-ui-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout-compose", version.ref = "constraint" }
androidx-navigation = { group = "org.jetbrains.androidx.navigation", name = "navigation-compose", version.ref = "navigation" }
androidx-viewmodel-compose = { group = "org.jetbrains.androidx.lifecycle", name = "lifecycle-viewmodel-compose", version.ref = "lifecycle" }
lottie-compose = { module = "com.airbnb.android:lottie-compose", version.ref = "lottie" }
coil-compose = { group = "io.coil-kt.coil3", name = "coil-compose", version.ref = "coil" }
coil-ktor = { group = "io.coil-kt.coil3", name = "coil-network-ktor3", version.ref = "coil" }
#zxing
zxing-android-embedded = { module = "com.journeyapps:zxing-android-embedded", version.ref = "zxingAndroidEmbedded" }
core = { module = "com.google.zxing:core", version.ref = "core" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }

#koin
koin-bom = { module = "io.insert-koin:koin-bom", version.ref = "koin" }
koin-core = { module = "io.insert-koin:koin-core" }
koin-android = { module = "io.insert-koin:koin-android" }
koin-compose = { module = "io.insert-koin:koin-compose" }
koin-compose-viewmodel = { module = "io.insert-koin:koin-compose-viewmodel" }

#ktor
ktorCore = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktorContentNegotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
ktorOkhttp = { module = "io.ktor:ktor-client-okhttp", version.ref = "ktor" }
ktorDarwin = { group = "io.ktor", name = "ktor-client-darwin", version.ref = "ktor" }
ktorSerialization = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }
ktorLogger = { module = "io.ktor:ktor-client-logging", version.ref = "ktor" }

#kotlinx
kotlinx-serialization = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization" }
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinx-datetime" }
kotlinx-coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }

#googleService
play-services-auth = { module = "com.google.android.gms:play-services-auth", version.ref = "playServicesAuth" }

#firebase
firebase-auth = { module = "com.google.firebase:firebase-auth", version.ref = "firebase-auth" }
firebase-auth-ktx = { module = "com.google.firebase:firebase-auth-ktx", version.ref = "firebase-auth" }
firebase-firestore-ktx = { module = "com.google.firebase:firebase-firestore-ktx", version.ref = "firebase-firestore-ktx" }
firebase-storage-ktx = { module = "com.google.firebase:firebase-storage-ktx", version.ref = "firebase-storage-ktx" }
firebase-database-ktx = { module = "com.github.skydoves:firebase-database-ktx", version.ref = "firebaseKtx" }

# Dependencies of the included build-logic
android-gradle-plugin = { module = "com.android.tools.build:gradle", version.ref = "agp" }
kotlin-gradle-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
compose-gradlePlugin = { module = "org.jetbrains.compose:org.jetbrains.compose.gradle.plugin", version.ref = "composePlugin" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
jetbrains-compose = { id = "org.jetbrains.compose", version.ref = "composePlugin" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
google-play-services = { id = "com.google.gms.google-services", version.ref = "playServices" }
serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }


